- id: '1665437965146'
  alias: Turn off Front washroom lights
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.switchlinc_dimmer_1d_4a_dc
    to: 'on'
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.enable_front_washroom_automation
    state: 'on'
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.switchlinc_dimmer_1d_4a_dc
  mode: single
- id: '1665764761019'
  alias: front-washroom.fan.auto-off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.front_washroom_exhaust_fan
    to: 'on'
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.enable_front_washroom_automation
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.front_washroom_exhaust_fan
  mode: single
- id: '1667518856937'
  alias: guest-washroom.light.auto-off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.keypad_with_dimmer_40_fe_83_main
    to: 'on'
    for:
      hours: 0
      minutes: 45
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.enable_guest_washroom_automation
    state: 'on'
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.keypad_with_dimmer_40_fe_83_main
  mode: single
- id: '1676647760080'
  alias: alert.laundry.washer.cycle_complete
  description: Send a notification when the washer power drops below 10W
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.washer
      starting_threshold: 50
      finishing_threshold: 5
      actions:
      - service: notify.mobile_app_vics_iphone
        data:
          message: Washer cycle has completed
          title: Washer
      pre_actions: []
      finishing_hysteresis: 5
      starting_hysteresis: 5
- id: '1676648187093'
  alias: alert.laundry.dryer.cycle_complete
  description: Send a notification when dryer power drops below 5W
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.dryer
      actions:
      - service: notify.mobile_app_vics_iphone
        data:
          message: Dryer cycle has completed
          title: Dryer
      pre_actions:
      - service: notify.mobile_app_vics_iphone
        data:
          message: Dryer cycle start detected
          title: Dryer
      - service: input_select.select_option
        data:
          option: Running
        target:
          entity_id: input_select.dryer
      starting_threshold: 50
      finishing_threshold: 20
      starting_hysteresis: 5
- id: '1684106940271'
  alias: Turn off pool pump
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.enable_pool_pump_schedule
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.on_off_outlet_57_87_64_bottom
  mode: single
- id: '1684106995925'
  alias: Turn on pool pump
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition:
  - condition: state
    entity_id: input_boolean.enable_pool_pump_schedule
    state: 'on'
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.on_off_outlet_57_87_64_bottom
  mode: single
- id: '1693015446407'
  alias: alert.lightning
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.lightning_detector_storm_distance
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_vics_iphone
    data:
      message: 'Lightning '
  mode: single
- id: '1697241814928'
  alias: 'Turn off Front decorative lights '
  description: ''
  trigger:
  - platform: time
    at: 02:00:00
  condition: []
  action:
  - type: turn_off
    device_id: c9f911ae71529f83ceffc4b1ac06d494
    entity_id: 5d8f83bc7d4685f564e60eb7c81a26a2
    domain: light
  - type: turn_off
    device_id: 76fa849c2440764efaf4ae53e97c1121
    entity_id: 48daa5444c62309be68111d06ea9d4e1
    domain: switch
  mode: single
- id: '1697242091947'
  alias: light.front_yard.led_string.on
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - type: turn_on
    device_id: c9f911ae71529f83ceffc4b1ac06d494
    entity_id: 5d8f83bc7d4685f564e60eb7c81a26a2
    domain: light
  - device_id: c9f911ae71529f83ceffc4b1ac06d494
    domain: select
    entity_id: 4dfba050af17852cc39434ab4f00d760
    type: select_first
  - type: turn_on
    device_id: 76fa849c2440764efaf4ae53e97c1121
    entity_id: 48daa5444c62309be68111d06ea9d4e1
    domain: switch
    enabled: false
  mode: single
- id: '1706893400957'
  alias: server-room.lights.door-activated [on]
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.door_sensor_contact
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.server_room_main_lights
  mode: single
- id: '1706893459258'
  alias: server-room.lights.door-activated [off]
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.door_sensor_contact
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.server_room_main_lights
  mode: single
- id: '1707271189445'
  alias: Keypad control recessed lights on
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.keypad_with_dimmer_40_fe_83_button_a
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.family_room_main_lights
  mode: single
- id: '1707271294541'
  alias: Keypad control recessed lights off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.keypad_with_dimmer_40_fe_83_button_a
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.family_room_main_lights
  mode: single
- id: '1707950316618'
  alias: Turn on Office Dimly
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.ceiling_lights_button_a
    from:
    to: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.ceiling_lights_button_a
  - service: light.turn_on
    target:
      device_id: e22babe121846f66115b86b635fa8235
    data:
      brightness_pct: 15
  mode: single
- id: '1708042561159'
  alias: light.office.presence
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_sensor_presence
    to: 'on'
    from:
    id: office-occupied
  - platform: state
    entity_id:
    - binary_sensor.presence_sensor_presence
    from:
    to: 'off'
    for:
      hours: 0
      minutes: 1
      seconds: 0
    id: office-vacant
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - office-occupied
      sequence:
      - service: light.turn_on
        metadata: {}
        data:
          brightness_pct: 20
        target:
          device_id: e22babe121846f66115b86b635fa8235
      - service: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 255
          - 255
          - 255
          brightness: 255
        target:
          entity_id: light.led_strip
    - conditions:
      - condition: trigger
        id:
        - office-vacant
      sequence:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          area_id: office
  mode: single
- id: '1709656644999'
  alias: alert.hot_water_tank_duration
  description: Send an alert if the hot water tank has drawn over 2000W for an extended
    period
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.water_heater
    for:
      hours: 0
      minutes: 45
      seconds: 0
    above: 2000
  condition: []
  action:
  - service: notify.mobile_app_vics_iphone
    metadata: {}
    data:
      title: Water Heater
      message: Exceeded On-Time
  mode: single
- id: '1710262972462'
  alias: alert.server_room.leak_sensor.leak_detected
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 33cff89280cf18d572d1c4d782a92e67
    entity_id: a21d5959f9072cf9aac458ca138550fe
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 15
  condition: []
  action:
  - service: notify.mobile_app_vics_iphone
    metadata: {}
    data:
      message: Moisture detected
      title: Leak Sensor
  mode: single
- id: '1710281136140'
  alias: alert.server_room.leak_senssor.battery_low
  description: ''
  trigger:
  - type: bat_low
    platform: device
    device_id: 33cff89280cf18d572d1c4d782a92e67
    entity_id: 4971e3f4f730e5e9339f39520e01a376
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition: []
  action:
  - service: notify.mobile_app_vics_iphone
    metadata: {}
    data:
      message: 'Replace batteries '
      title: Leak Sensor
  mode: single
- id: '1711584978796'
  alias: lights.all.turn_off
  description: ''
  trigger: []
  condition: []
  action:
  - service: light.turn_off
    entity_id: all
  mode: single
