- id: '1657646410029'
  alias: Turn on Amp at 7am
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - service: media_player.turn_on
    data: {}
    target:
      entity_id: media_player.denon_3808ci
  mode: single
- id: '1657646458863'
  alias: Turn Amp off at 10pm
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: media_player.turn_off
    data: {}
    target:
      entity_id: media_player.denon_3808ci
  mode: single
- id: '1665437965146'
  alias: Turn off Front washroom lights
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.switchlinc_dimmer_1d_4a_dc
    to: 'on'
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.enable_front_washroom_automation
    state: 'on'
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.switchlinc_dimmer_1d_4a_dc
  mode: single
- id: '1665764761019'
  alias: Automatically turn off front washroom fan
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.front_washroom_exhaust_fan
    to: 'on'
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.enable_front_washroom_automation
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.front_washroom_exhaust_fan
  mode: single
- id: '1667518856937'
  alias: Guest Washroom Light - Auto Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.keypad_with_dimmer_40_fe_83_main
    to: 'on'
    for:
      hours: 0
      minutes: 45
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.enable_guest_washroom_automation
    state: 'on'
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.keypad_with_dimmer_40_fe_83_main
  mode: single
- id: '1676647760080'
  alias: Washer Cycle Complete
  description: Send a notification when the washer power drops below 10W
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.washer
      starting_threshold: 50
      finishing_threshold: 5
      actions:
      - service: notify.mobile_app_vics_iphone
        data:
          message: Washer cycle has completed
          title: Washer
      pre_actions: []
      finishing_hysteresis: 5
      starting_hysteresis: 5
- id: '1676648187093'
  alias: Dryer cycle completed
  description: Send a notification when dryer power drops below 5W
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.dryer
      actions:
      - service: notify.mobile_app_vics_iphone
        data:
          message: Dryer cycle has completed
          title: Dryer
      pre_actions:
      - service: notify.mobile_app_vics_iphone
        data:
          message: Dryer cycle start detected
          title: Dryer
      - service: input_select.select_option
        data:
          option: Running
        target:
          entity_id: input_select.dryer
      starting_threshold: 50
      finishing_threshold: 20
      starting_hysteresis: 5
- id: '1683247135769'
  alias: Office lights on
  description: ''
  trigger:
  - platform: time
    at: 07:30:00
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - type: turn_on
    device_id: dd7fd84bd3a962790d9801dac4fa22fb
    entity_id: light.switchlinc_dimmer_2f_cd_b1
    domain: light
    brightness_pct: 15
  mode: single
- id: '1684106940271'
  alias: Turn off pool pump
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.enable_pool_pump_schedule
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.on_off_outlet_57_87_64_bottom
  mode: single
- id: '1684106995925'
  alias: Turn on pool pump
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition:
  - condition: state
    entity_id: input_boolean.enable_pool_pump_schedule
    state: 'on'
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.on_off_outlet_57_87_64_bottom
  mode: single
- id: '1693015446407'
  alias: Lightning alert
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.lightning_detector_storm_distance
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_vics_iphone
    data:
      message: 'Lightning '
  mode: single
- id: '1697058234249'
  alias: Office lights off
  description: ''
  trigger:
  - platform: time
    at: '16:30:00'
  condition: []
  action:
  - type: turn_off
    device_id: dd7fd84bd3a962790d9801dac4fa22fb
    entity_id: bb52b494ce3a018028759b914a26f1e3
    domain: light
  mode: single
- id: '1697241814928'
  alias: 'Turn off Front decorative lights '
  description: ''
  trigger:
  - platform: time
    at: 02:00:00
  condition: []
  action:
  - type: turn_off
    device_id: c9f911ae71529f83ceffc4b1ac06d494
    entity_id: 5d8f83bc7d4685f564e60eb7c81a26a2
    domain: light
  - type: turn_off
    device_id: 76fa849c2440764efaf4ae53e97c1121
    entity_id: 48daa5444c62309be68111d06ea9d4e1
    domain: switch
  mode: single
- id: '1697242091947'
  alias: 'Turn on Front decorative lights '
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - type: turn_on
    device_id: c9f911ae71529f83ceffc4b1ac06d494
    entity_id: 5d8f83bc7d4685f564e60eb7c81a26a2
    domain: light
  - device_id: c9f911ae71529f83ceffc4b1ac06d494
    domain: select
    entity_id: 4dfba050af17852cc39434ab4f00d760
    type: select_first
  - type: turn_on
    device_id: 76fa849c2440764efaf4ae53e97c1121
    entity_id: 48daa5444c62309be68111d06ea9d4e1
    domain: switch
    enabled: false
  mode: single
- id: '1706893400957'
  alias: Door Activated Server Light On
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.server_room_monitor_server_room_door
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.server_room_main_lights
  mode: single
- id: '1706893459258'
  alias: Door Activated Server Light Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.server_room_monitor_server_room_door
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.server_room_main_lights
  mode: single

# https://community.home-assistant.io/t/snmp-bandwidth-monitor/7122
# https://community.home-assistant.io/t/snmp-bandwidth-monitor-using-statistics-and-a-utility-meter/176971
- alias: "Monitor Inbound Internet Traffic"
  id: "244f20ae-8cc6-4442-b3aa-0336763508f8"
  trigger:
    platform: state
    entity_id: sensor.snmp_wan_in
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.wan_traffic_delta_in
        value: >-
          {# safe delta catering for wrap-around of a 32-bit unsigned int (snmp counter is 32-bit unsigned int) #}
          {# basically taking 2's complement #}
          {% set from = trigger.from_state.state | int(0) %}
          {% set to = trigger.to_state.state | int(0) %}
          {% set traffic_delta = (to - from) if (to >= from) else (4294967295 - from + to + 1) %}
          {% set time_delta = as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) %}
          {{ (traffic_delta * 8) / time_delta }}

- alias: "Monitor Outbound Internet Traffic"
  id: "719b1fd6-bfc1-40b3-bf0e-5a07cff11aea"
  trigger:
    platform: state
    entity_id: sensor.snmp_wan_out
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.wan_traffic_delta_out
        value: >-
          {# safe delta catering for wrap-around of a 32-bit unsigned int (snmp counter is 32-bit unsigned int) #}
          {# basically taking 2's complement #}
          {% set from = trigger.from_state.state | int(0) %}
          {% set to = trigger.to_state.state | int(0) %}
          {% set traffic_delta = (to - from) if (to >= from) else (4294967295 - from + to + 1) %}
          {% set time_delta = as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) %}
          {{ (traffic_delta * 8) / time_delta }}

