- id: '1657646410029'
  alias: Turn on Amp at 7am
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - service: media_player.turn_on
    data: {}
    target:
      entity_id: media_player.denon_3808ci
  mode: single
- id: '1657646458863'
  alias: Turn Amp off at 10pm
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: media_player.turn_off
    data: {}
    target:
      entity_id: media_player.denon_3808ci
  mode: single
- id: '1665437965146'
  alias: Turn off Front washroom lights
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.switchlinc_dimmer_1d_4a_dc
    to: 'on'
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.switchlinc_dimmer_1d_4a_dc
  mode: single
- id: '1665764761019'
  alias: Automatically turn off front washroom fan
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.front_washroom_exhaust_fan
    to: 'on'
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.front_washroom_exhaust_fan
  mode: single
- id: '1667518856937'
  alias: Guest Washroom Light - Auto Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.keypad_with_dimmer_40_fe_83_main
    to: 'on'
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.keypad_with_dimmer_40_fe_83_main
  mode: single
- id: '1669723280275'
  alias: Restart Hoymiles Add-On
  description: Occasionally the add-on times out - this will restart it
  trigger:
  - platform: state
    entity_id:
    - sensor.solarh_655250_capacitor
    to: unavailable
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: hassio.addon_restart
    data:
      addon: 44349f66_hoymiles_solardata
  mode: single
- id: '1672349972409'
  alias: Button A on
  description: Turn on family room lights
  trigger:
  - platform: state
    entity_id:
    - switch.keypad_with_dimmer_40_fe_83_button_a
    to: 'on'
  condition: []
  action:
  - type: turn_on
    device_id: a84a1a1923ae705475e7dd6f7ecb7170
    entity_id: light.family_room_main_lights
    domain: light
    brightness_pct: 75
  mode: single
- id: '1672350161457'
  alias: Button A off
  description: 'Turn off family room lights '
  trigger:
  - platform: state
    entity_id:
    - switch.keypad_with_dimmer_40_fe_83_button_a
    to: 'off'
  condition: []
  action:
  - type: turn_off
    device_id: a84a1a1923ae705475e7dd6f7ecb7170
    entity_id: light.family_room_main_lights
    domain: light
  mode: single
- id: '1676647760080'
  alias: Washer Cycle Complete
  description: Send a notification when the washer power drops below 10W
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.washer
      starting_threshold: 25
      finishing_threshold: 5
      actions:
      - service: notify.mobile_app_vics_iphone
        data:
          message: Washer cycle has completed
          title: Washer
      pre_actions:
      - service: notify.mobile_app_vics_iphone
        data:
          message: Washer cycle start detected
          title: Washer
      finishing_hysteresis: 5
      starting_hysteresis: 2
- id: '1676648187093'
  alias: Dryer cycle completed
  description: Send a notification when dryer power drops below 5W
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.dryer
      actions:
      - service: notify.mobile_app_vics_iphone
        data:
          message: Dryer cycle has completed
          title: Dryer
      pre_actions:
      - service: notify.mobile_app_vics_iphone
        data:
          message: Dryer cycle start detected
          title: Dryer
      - service: input_select.select_option
        data:
          option: Running
        target:
          entity_id: input_select.dryer
      starting_threshold: 50
      finishing_threshold: 20
      starting_hysteresis: 2
