- id: '1665437965146'
  alias: Turn off Front washroom lights
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.switchlinc_dimmer_1d_4a_dc
    to: 'on'
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.enable_front_washroom_automation
    state: 'on'
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.switchlinc_dimmer_1d_4a_dc
  mode: single
- id: '1667518856937'
  alias: auto_off.guest_washroom.light
  description: ''
  triggers:
  - entity_id:
    - light.keypad_with_dimmer_40_fe_83_main
    to: 'on'
    for:
      hours: 0
      minutes: 45
      seconds: 0
    trigger: state
  conditions:
  - condition: state
    entity_id: input_boolean.enable_guest_washroom_automation
    state: 'on'
  actions:
  - data: {}
    target:
      entity_id: light.keypad_with_dimmer_40_fe_83_main
    action: light.turn_off
  mode: single
- id: '1676647760080'
  alias: alert.laundry.washer.cycle_complete
  description: Send a notification when the washer power drops below 10W
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.washer
      starting_threshold: 50
      finishing_threshold: 5
      actions:
      - action: notify.mobile_app_vics_iphone
        data: {}
      pre_actions: []
      finishing_hysteresis: 5
      starting_hysteresis: 5
- id: '1676648187093'
  alias: alert.laundry.dryer.cycle_complete
  description: Send a notification when dryer power drops below 5W
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.dryer
      actions:
      - data:
          message: Dryer cycle has completed
          title: Dryer
        action: notify.mobile_app_vics_iphone
      pre_actions: []
      starting_threshold: 50
      finishing_threshold: 20
      starting_hysteresis: 5
- id: '1684106940271'
  alias: Turn off pool pump
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.enable_pool_pump_schedule
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    target:
      device_id: 76fa849c2440764efaf4ae53e97c1121
  mode: single
- id: '1684106995925'
  alias: Turn on pool pump
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition:
  - condition: state
    entity_id: input_boolean.enable_pool_pump_schedule
    state: 'on'
  action:
  - service: switch.turn_on
    data: {}
    target:
      device_id: 76fa849c2440764efaf4ae53e97c1121
  mode: single
- id: '1693015446407'
  alias: alert.lightning
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.lightning_detector_storm_distance
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_vics_iphone
    data:
      message: 'Lightning '
  mode: single
- id: '1697241814928'
  alias: 'Turn off Front decorative lights '
  description: ''
  triggers:
  - at: 02:00:00
    trigger: time
  conditions: []
  actions:
  - type: turn_off
    device_id: c9f911ae71529f83ceffc4b1ac06d494
    entity_id: 5d8f83bc7d4685f564e60eb7c81a26a2
    domain: light
  mode: single
- id: '1697242091947'
  alias: light.front_yard.led_string.on
  description: ''
  triggers:
  - event: sunset
    offset: 0
    trigger: sun
  conditions: []
  actions:
  - type: turn_on
    device_id: c9f911ae71529f83ceffc4b1ac06d494
    entity_id: 5d8f83bc7d4685f564e60eb7c81a26a2
    domain: light
  - device_id: c9f911ae71529f83ceffc4b1ac06d494
    domain: select
    entity_id: 4dfba050af17852cc39434ab4f00d760
    type: select_first
  mode: single
- id: '1706893400957'
  alias: server-room.lights.door-activated [on]
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.server_room_door_sensor_contact
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.server_room_main_lights
  mode: single
- id: '1706893459258'
  alias: server-room.lights.door-activated [off]
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.server_room_door_sensor_contact
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.server_room_main_lights
  mode: single
- id: '1707271189445'
  alias: Keypad control recessed lights on
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.keypad_with_dimmer_40_fe_83_button_a
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.family_room_main_lights
  mode: single
- id: '1707271294541'
  alias: Keypad control recessed lights off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.keypad_with_dimmer_40_fe_83_button_a
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.family_room_main_lights
  mode: single
- id: '1707950316618'
  alias: Turn on Office Dimly
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.ceiling_lights_button_a
    from:
    to: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.ceiling_lights_button_a
  - service: light.turn_on
    target:
      device_id: e22babe121846f66115b86b635fa8235
    data:
      brightness_pct: 15
  - service: light.turn_on
    metadata: {}
    data:
      rgb_color:
      - 255
      - 255
      - 255
    target:
      device_id: 4ca2146b55d50c33072f44ba92ad9821
  mode: single
- id: '1708042561159'
  alias: light.office.presence
  description: ''
  triggers:
  - entity_id:
    - binary_sensor.office_presence_sensor_presence
    to: 'on'
    from:
    id: office-occupied
    trigger: state
  - entity_id:
    - binary_sensor.office_presence_sensor_presence
    from:
    to: 'off'
    for:
      hours: 0
      minutes: 1
      seconds: 0
    id: office-vacant
    trigger: state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - office-occupied
      sequence:
      - metadata: {}
        data:
          brightness_pct: 20
        target:
          device_id: e22babe121846f66115b86b635fa8235
        action: light.turn_on
      - metadata: {}
        data:
          rgb_color:
          - 0
          - 0
          - 255
          brightness: 255
        target:
          device_id: 4ca2146b55d50c33072f44ba92ad9821
        action: light.turn_on
    - conditions:
      - condition: trigger
        id:
        - office-vacant
      sequence:
      - metadata: {}
        data: {}
        target:
          area_id: office
        action: light.turn_off
      - metadata: {}
        data: {}
        target:
          device_id: 4ca2146b55d50c33072f44ba92ad9821
        action: light.turn_off
  mode: single
- id: '1709656644999'
  alias: alert.hot_water_tank_duration
  description: Send an alert if the hot water tank has drawn over 2000W for an extended
    period
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.water_heater
    for:
      hours: 1
      minutes: 30
      seconds: 0
    above: 2000
  condition: []
  action:
  - service: notify.mobile_app_vics_iphone
    metadata: {}
    data:
      title: Water Heater
      message: Exceeded On-Time
  mode: single
- id: '1710262972462'
  alias: alert.server_room.leak_sensor.leak_detected
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 33cff89280cf18d572d1c4d782a92e67
    entity_id: a21d5959f9072cf9aac458ca138550fe
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 15
  condition: []
  action:
  - service: notify.mobile_app_vics_iphone
    metadata: {}
    data:
      message: Moisture detected
      title: Leak Sensor
  mode: single
- id: '1710281136140'
  alias: alert.server_room.leak_sensor.battery_low
  description: ''
  triggers:
  - type: bat_low
    device_id: 33cff89280cf18d572d1c4d782a92e67
    entity_id: 4971e3f4f730e5e9339f39520e01a376
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 30
    trigger: device
  conditions: []
  actions:
  - metadata: {}
    data:
      message: 'Replace batteries '
      title: Leak Sensor
    action: notify.mobile_app_vics_iphone
  mode: single
- id: '1711584978796'
  alias: lights.all.turn_off
  description: ''
  trigger: []
  condition: []
  action:
  - service: light.turn_off
    entity_id: all
  mode: single
- id: '1624586003695'
  alias: RTL433 MQTT message_type Demuxer
  description: Split rtl_433/# signals into msg topics, if message_type exists
  trigger:
  - platform: mqtt
    topic: rtl_433/+/+
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.message_type != null }}'
  action:
  - service: mqtt.publish
    data:
      payload: '{{trigger.payload}}'
      topic: rtl_433/{{trigger.payload_json.model or "UnknownModel"}}/{{trigger.payload_json.id
        or "UnknownId"}}/msg{{trigger.payload_json.message_type}}
  mode: single
- id: '1731859032459'
  alias: auto_off.master_bathroom.shower_fan
  description: ''
  triggers:
  - trigger: event
    event_type: timer.finished
    event_data:
      entity_id: timer.shower_fan_timer
    id: Timer Finished
  - type: turned_on
    device_id: ab4e7922c8937417d8280f022bd683ed
    entity_id: 4a0cca88ccd7da8173342263ac554bb7
    domain: switch
    trigger: device
    for:
      hours: 0
      minutes: 0
      seconds: 1
    id: Fan turned on
  - type: turned_off
    device_id: ab4e7922c8937417d8280f022bd683ed
    entity_id: 4a0cca88ccd7da8173342263ac554bb7
    domain: switch
    trigger: device
    id: Fan turned off
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Fan turned on
      sequence:
      - action: timer.start
        target:
          entity_id: timer.shower_fan_timer
        data:
          duration:
            hours: 0
            minutes: '{{ states(''input_number.shower_timer'') | int }}'
            seconds: 0
            milliseconds: 0
    - conditions:
      - condition: trigger
        id:
        - Fan turned off
      sequence:
      - action: timer.cancel
        target:
          entity_id: timer.shower_fan_timer
        data: {}
    - conditions:
      - condition: trigger
        id:
        - Timer Finished
      sequence:
      - type: turn_off
        device_id: ab4e7922c8937417d8280f022bd683ed
        entity_id: 4a0cca88ccd7da8173342263ac554bb7
        domain: switch
  mode: single
- id: '1731860780622'
  alias: auto_off.front_washroom.exhaust_fan
  description: ''
  triggers:
  - trigger: event
    event_type: timer.finished
    event_data:
      entity_id: timer.front_bathroom_fan_timer
    id: Timer Finished
  - type: turned_on
    device_id: bf9a119ceeac695161a680e323abb368
    entity_id: ff7f7ba46fd70a450c88b4e419f1ef0c
    domain: switch
    trigger: device
    id: Fan turned on
  - type: turned_off
    device_id: bf9a119ceeac695161a680e323abb368
    entity_id: ff7f7ba46fd70a450c88b4e419f1ef0c
    domain: switch
    trigger: device
    id: Fan turned off
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Fan turned on
      sequence:
      - action: timer.start
        target:
          entity_id: timer.front_bathroom_fan_timer
        data:
          duration: 00:35:00
    - conditions:
      - condition: trigger
        id:
        - Fan turned off
      sequence:
      - action: timer.cancel
        data: {}
        target:
          entity_id: timer.front_bathroom_fan_timer
    - conditions:
      - condition: trigger
        id:
        - Timer Finished
      sequence:
      - type: turn_off
        device_id: bf9a119ceeac695161a680e323abb368
        entity_id: ff7f7ba46fd70a450c88b4e419f1ef0c
        domain: switch
  mode: single
- id: '1732845214224'
  alias: Christmas
  description: ''
  triggers:
  - event_data:
      actionID: 13870D14-F29D-4979-BAAD-0502A06DB0CD
    event_type: ios.action_fired
    trigger: event
  conditions: []
  actions:
  - type: turn_on
    device_id: a36db20fbe381d6a63674e7044c23bd2
    entity_id: 9ee6ecc8fe99d7bcf60bc21122e16f79
    domain: switch
  - type: turn_on
    device_id: 262c6ec6fa515299fa25e2595fa54b88
    entity_id: cf56c5d6f5e6bb685dc59a9988d703c0
    domain: light
  - type: turn_on
    device_id: 61a72ee7ac5591874b6e7584583fbda7
    entity_id: 7c726eb533f12bdc1de4a7243c551baa
    domain: switch
  - type: turn_on
    device_id: 00f34f2e80cb9816e8c25a8f8adfb18e
    entity_id: 57325e3a2f547279009b1d7c2011703f
    domain: light
  mode: single
- id: '1732986664599'
  alias: Turn on Downstairs heating
  description: ''
  triggers:
  - trigger: time
    at: '15:00:00'
  conditions:
  - condition: numeric_state
    entity_id: sensor.mysa_698214_current_temperature
    below: 20
  actions:
  - action: climate.set_temperature
    metadata: {}
    data:
      temperature: 24
      hvac_mode: heat
    target:
      entity_id: climate.mysa_698214_thermostat
  mode: single
- id: '1732986769207'
  alias: Turn off downstairs heating
  description: ''
  triggers:
  - trigger: time
    at: '21:00:00'
  conditions: []
  actions:
  - action: climate.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: climate.mysa_698214_thermostat
  mode: single
- id: '1754785734123'
  alias: 'Motion-activated Garage lights '
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.garage_motion
      light_target:
        area_id: garage
