
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: error
    #  logs:
    #    homeassistant.components.shell_command: debug


recorder:
  db_url: !secret psql_string
  db_retry_wait: 15
  exclude:
    domains:
      - automation
      - updater
    entity_globs:
      - sensor.weather_*
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date
    event_types:
      - call_service

frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5
  cors_allowed_origins: 
    - https://homeassistant.mvgrafx.net
  trusted_proxies:
    - !secret proxy_ip

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
mqtt: !include mqtt.yaml
sensor: !include sensor.yaml
template: !include template.yaml
utility_meter: !include utility_meter.yaml
input_number: !include input_number.yaml
media_player: !include media_player.yaml
shell_command: !include shell_commands.yaml

