sensor:
  #  - name: 'Home Electricity Watts'
  #  state_topic: 'rtl_433/ubuntupi/devices/Efergy-e2CT/60867/current'
  #  unit_of_measurement: W
  #  value_template: "{{ (value | float * 120) | round(2) }}"
  #  device_class: power

  - name: 'Bell Jitter'
    state_topic: 'bandwidth/bell-aliant'
    unit_of_measurement: 'ms'
    value_template: "{{value_json.jitter}}"

  - name: 'Bell Ping'
    state_topic: 'bandwidth/bell-aliant'
    unit_of_measurement: 'ms'
    value_template: "{{value_json.ping}}"

  - name: 'Bell Upload'
    state_topic: 'bandwidth/bell-aliant'
    unit_of_measurement: 'Mbps'
    value_template: "{{ (value_json.upload | int / 1048576) | round(0) }}"

  - name: 'Bell Download'
    state_topic: 'bandwidth/bell-aliant'
    unit_of_measurement: 'Mbps'
    value_template: "{{ (value_json.download | int / 1048576) | round(0) }}"
