- platform: statistics
  name: '24h Upload Average'
  entity_id: sensor.bell_upload
  sampling_size: 20
  state_characteristic: mean
  max_age:
    hours: 24

- platform: statistics
  name: '24h Download Average'
  entity_id: sensor.bell_download
  sampling_size: 20
  state_characteristic: mean
  max_age:
    hours: 24

- platform: template
  sensors:
    electricity_kwh_unit_price:
      friendly_name_template: 'NSPI Tariff'
      value_template: 0.17547
      unit_of_measurement: 'CAD/kWh'
    last_lightning_event:
      unique_id: lightning_last_event
      friendly_name_template: 'Last Lightning Event'
      value_template: "{{ states['sensor.lightning_detector_storm_distance'].last_changed }}"
      device_class: timestamp

- platform: snmp
  name: snmp_wan_in
  host: 192.168.5.1
  community: public
  version: 2c
  baseoid: 1.3.6.1.2.1.31.1.1.1.6.3  # ifInOctets.14
  unit_of_measurement: octets
- platform: snmp
  name: snmp_wan_out
  host: 192.168.5.1
  community: public
  version: 2c
  baseoid: 1.3.6.1.2.1.31.1.1.1.10.3  # ifOutOctets.14
  unit_of_measurement: octets
- platform: statistics
  name: 'Internet Traffic In'
  entity_id: sensor.internet_speed_in
  state_characteristic: mean
  sampling_size: 100
  max_age:
    minutes: 1
- platform: statistics
  name: 'Internet Traffic Out'
  entity_id: sensor.internet_speed_out
  state_characteristic: mean
  sampling_size: 100
  max_age:
    minutes: 1
- platform: template
  sensors:
    internet_speed_in:
      value_template: '{{ ((states.input_number.wan_traffic_delta_in.state | float ) / 1000000 ) | round(3) }}'
      unit_of_measurement: 'Mbps'
    internet_speed_out:
      value_template: '{{ ((states.input_number.wan_traffic_delta_out.state | float ) / 1000000 ) | round(3) }}'
      unit_of_measurement: 'Mbps'
    internet_usage_in:
      value_template: '{{ ((states.input_number.wan_traffic_delta_in.state | float ) / 1000000000 / 8 ) | round(3) }}'
      unit_of_measurement: 'GB'
    internet_usage_out:
      value_template: '{{ ((states.input_number.wan_traffic_delta_out.state | float ) / 1000000000 / 8 ) | round(3) }}'
      unit_of_measurement: 'GB'
