substitutions:
  name: athom-smart-plug-v3-50ba64
  friendly_name: Athom Plug V3 50ba64

packages:
  - !include common/athom-smart-plug-v3.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: Aqj6ED184XDSGkEDkGwZC/aVZnyv2eyUVS8RZzeyvb8=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.10.174

bluetooth_proxy:
  active: true