substitutions:
  name: athom-smart-plug-v2-9d9438
  friendly_name: Plex Server Power
packages:
  Athom_Technology.Smart_Plug_V2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 6n0cJ/ssJGazeQzTU+sSRxdQO3qTA/lFrNteAAaV1Ww=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.10.210
