substitutions:
  name: athom-smart-plug-v3-50a098
  friendly_name: Athom Plug V3 50a098
packages:
  Athom_Technology.Smart_Plug_V3: github://athom-tech/esp32-configs/athom-smart-plug.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: T3IgP2TuUHg3iHNwoVGDL+BIuLviankqN2tx008Oo+A=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.10.132

bluetooth_proxy:
  active: true
