substitutions:
  name: athom-smart-plug-v2
  friendly_name: Docker Server Power
  hide_energy_sensor: "true"
  early_pin_init: "true"
  log_level: "INFO"
  timezone: "America/Halifax"

packages:
  - !include common/common8266.yaml
  - !include common/athom-smart-plug-v2.yaml

api:
  encryption:
    key: "szw9iWMxybb3FGPTI0r0sVS61in/geh478qV72F7hEo="

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.10.211