esphome:
  name: esphome-web-dcd340
  friendly_name: Lightning Detector 

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "lXRm9dhl2p6oMxWxnL1OOjZcFvIwsrTu/vOifJ4TOm8="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 9 #8.5-20
  power_save_mode: HIGH #HIGH NONE LIGHT
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-Dcd340"
    password: "3QNyQKG2ln4z"

captive_portal:

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

as3935_spi:
  cs_pin: GPIO15
  irq_pin: 
    number: GPIO5
  indoor: false
  noise_level: 2
  spike_rejection: 2      # Default 2
  lightning_threshold: 1
  mask_disturber: false
  div_ratio: 0
  capacitance: 5
  watchdog_threshold: 2

sensor:
  - platform: as3935
    lightning_energy:
      name: "Lightning Energy"
    distance:
      name: "Storm Distance"

binary_sensor:
  - platform: as3935
    name: "Storm Alert"  