esphome:
  name: family-room-monitor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "151183c5cb5f49fee00c51673ed52030"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Family-Room-Monitor"
    password: "627JWccN8b7T"

# Example configuration entry
sensor:
  - platform: dht
    pin: D2
    model: AM2302
    temperature:
      name: "Family Room Temperature"
    humidity:
      name: "Family Room Humidity"
    update_interval: 60s