substitutions:
  friendly_name: Living Room
  name: living-room

packages:
  - !include common/common8266.yaml

esp8266:
  board: nodemcuv2

# Enable Home Assistant API
api:
  encryption:
    key: "IGlzLAZLynaxN6ZVVua+TCGY7zS8GOPXFB8ky1sy3KM="

ota:
  - platform: esphome
    password: "13d4a4efda69e04a145bc6cce4db1dab"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.10.184

i2c:
  id: bus_a
  sda: 4
  scl: 5

sensor:
  - platform: aht10
    i2c_id: bus_a
    variant: AHT20
    temperature:
      id: aht_temp
      name: "Temperature"
    humidity:
      id: aht_humid
      name: "Humidity"
    update_interval: 60s

  - platform: ens160_i2c
    i2c_id: bus_a
    eco2:
      name: "eCO2"
    tvoc:
      name: "Total VOC"
    aqi:
      id: front_room_aqi
      name: "AQI"
    update_interval: 60s
    address: 0x53
    compensation:
      temperature: aht_temp
      humidity: aht_humid

text_sensor:
  - platform: template
    name: "Air Quality Rating"
    lambda: |-
      switch ( (int) (id(front_room_aqi).state) ) {
        case 1: return std::string("Excellent");
        case 2: return std::string("Good");
        case 3: return std::string("Moderate");
        case 4: return std::string("Poor");
        case 5: return std::string("Unhealthy");
        default: return std::string("Not Available");
      }