substitutions:
  friendly_name: Garage Monitor
  name: garage-monitor

packages:
  - !include common/common8266.yaml
  
esp8266:
  board: nodemcuv2

# Enable Home Assistant API
api:
  encryption:
    key: "izllBRgAAgCcaqpOJE0fRTPGKFu8UszBplfAzA68aWM="

ota:
  - platform: esphome
    password: "be3e8067bfafb49e24c5219f36ead490"
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.10.202
  
i2c:
  id: bus_a
  sda: 4
  scl: 5
  frequency: 800kHz
  #scan: true

sensor:
  - platform: sht4x
    id: env_sensor
    i2c_id: bus_a
    temperature:
      name: "Temperature"
      id: garage_temperature
    humidity:
      name: "Humidity"
      id: garage_humidity