esphome:
  name: lcd-char

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "iFvh9VFd9tWLIJK6wf7fNPFDl0JWKmYtyRQ9DInGCCY="

ota:
  password: "428c3982d8e654c66ed2603cc63a5e50"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lcd-Char Fallback Hotspot"
    password: "rL64GSDSoP27"

captive_portal:

sensor:
  - platform: homeassistant
    id: pool_temperature
    entity_id: sensor.pool_temperature
    internal: true

  - platform: homeassistant
    id: solar_power
    entity_id: sensor.solar_total
    internal: true

  - platform: homeassistant
    id: house_power
    entity_id: sensor.mains_import
    internal: true

  - platform: homeassistant
    id: output_to_grid
    entity_id: sensor.mains_export
    internal: true    

i2c:
  sda: D2
  scl: D1

display:
  - platform: lcd_pcf8574
    dimensions: 20x4
    address: 0x27
    update_interval: 10s
    lambda: |-
      it.print(0,0,"Pool temp:");
      it.print(0,1,"Solar gen:");
      it.print(0,2," Grid imp:");
      it.print(0,3," Grid exp:");
  
      it.printf(12,0, "%.1f\xDF""C", id(pool_temperature).state);
      it.printf(12,1, "%.1fW", id(solar_power).state);
      it.printf(12,2, "%.1fW", id(house_power).state);
      it.printf(12,3, "%.1fW", id(output_to_grid).state);

