esphome:
  name: oled-display

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret oled_api_key

ota:
  password: "e77e32dd7004ff7ec5c5cfa2972985f9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Oled-Display Fallback Hotspot"
    password: "eaDkljYiV8Ir"

sensor:
  - platform: homeassistant
    id: pool_temperature
    entity_id: sensor.pool_temperature
    internal: true
  - platform: homeassistant
    id: solar_power
    entity_id: sensor.solarh_655250_real_power
    internal: true

font:
  - file: 'arial.ttf'
    id: arial24
    size: 24
    
  - file: 'arial.ttf'
    id: arial32
    size: 32

i2c:
  sda: D1
  scl: D2

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    update_interval: 30s
    reset_pin: D0
    address: 0x3C
    lambda: |-
      // it.printf(64, 0, id(arial24), TextAlign::TOP_CENTER, "Pool");

      // Print outside temperature (from homeassistant sensor)
      if (id(pool_temperature).has_state()) {
        it.printf(64, 0, id(arial32), TextAlign::TOP_CENTER , "%.1f°C", id(pool_temperature).state);
      }

      if (id(solar_power).has_state()) {
        it.printf(64, 34, id(arial24), TextAlign::TOP_CENTER , "%.1fW", id(solar_power).state);
      }