esphome:
  name: oled-display

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret oled_api_key

ota:
  password: "e77e32dd7004ff7ec5c5cfa2972985f9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Oled-Display Fallback Hotspot"
    password: "eaDkljYiV8Ir"

sensor:
  - platform: homeassistant
    id: solar_generated
    entity_id: sensor.solar_total
    internal: true
  - platform: homeassistant
    id: grid_import
    entity_id: sensor.mains_import
    internal: true 

graph:
  - id: power_graph
    duration: 1h
    min_value: 0
    max_value: 20000
    width: 128
    height: 64
    border: false 
    traces:
      - sensor: solar_generated
        line_thickness: 1
        line_type: DOTTED
      - sensor: grid_import
        line_thickness: 1
        line_type: SOLID

font:
  - file: 'arial.ttf'
    id: arial24
    size: 24
    
  - file: 'arial.ttf'
    id: arial32
    size: 32

i2c:
  sda: D1
  scl: D2

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    update_interval: 10s
    reset_pin: D0
    address: 0x3C
    lambda: |-
      it.graph(0,0, id(power_graph));