substitutions:
  name: pool-monitor
  friendly_name: Pool Monitor
  timezone: "America/Halifax"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

packages:
  - !include common/common32.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "oGKK4EAWyWFZOubwPaogW9/D7YDskzInfFXHxpnwmNU="

ota:
  - platform: esphome
    password: "78c55db4090f844c156e1639ce818ec9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: template
    name: "Temperature"
    id: temperature
    update_interval: 60s
    lambda: |-
      return 0.0;
    unit_of_measurement: "ºC"
    device_class: temperature
