esphome:
  name: relay-board
  friendly_name: Relay Board

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "w/PxWvV1J5xnn0i36KM4H/N/b2ZLwz0G801jlWxYcCo="

ota:
  password: "26f244c1f14dc549800e96dfb9d605ff"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.10.207

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Relay-Board Fallback Hotspot"
    password: "NGbSd9DSWVRt"

captive_portal:
    
switch:
  - platform: gpio
    name: "Relay0"
    pin: GPIO4
  - platform: gpio
    name: "Relay1"
    pin: GPIO5