esphome:
  name: server-room-monitor
  friendly_name: Server Room Monitor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "7db75f445b389e259f6c9780f455686f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.10.203

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Server-Room-Monitor"
    password: "t77H9qIwI44j"

# Example configuration entry
sensor:
  - platform: dht
    pin: D2
    model: AM2302
    temperature:
      name: "Server Room Temperature"
    humidity:
      name: "Server Room Humidity"
    update_interval: 120s