substitutions:
  friendly_name: Server Room
  name: server-room-monitor

packages:
  - !include common/common8266.yaml

esp8266:
  board: nodemcuv2

# Enable Home Assistant API
api:
  encryption:
    key: "cbE2mBXgLbeFDMTFwH0cbtzZZ3ik6bW0LOOPW9iiQlQ="

ota:
  - platform: esphome
    password: "7db75f445b389e259f6c9780f455686f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.10.203

# Example configuration entry
sensor:
  - platform: dht
    pin: D2
    model: AM2302
    temperature:
      name: "Server Room Temperature"
    humidity:
      name: "Server Room Humidity"
    update_interval: 120s